// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYUhwsASuApT61HPP9oxhsNQZUlQ9oiSA',
    appId: '1:577701324258:web:ba5d3def403284cffd45bb',
    messagingSenderId: '577701324258',
    projectId: 'mynotes-492a9',
    authDomain: 'mynotes-492a9.firebaseapp.com',
    storageBucket: 'mynotes-492a9.appspot.com',
    measurementId: 'G-NWRQ29TB3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvLj9FzqWynCFWlpMthiEZpbo7Eqn8K7g',
    appId: '1:577701324258:android:7242421741552b32fd45bb',
    messagingSenderId: '577701324258',
    projectId: 'mynotes-492a9',
    storageBucket: 'mynotes-492a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIjaGtafuChqVz7-YdVRkyTtDUABtvTG0',
    appId: '1:577701324258:ios:ea75ad0835d04401fd45bb',
    messagingSenderId: '577701324258',
    projectId: 'mynotes-492a9',
    storageBucket: 'mynotes-492a9.appspot.com',
    iosBundleId: 'com.hello.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIjaGtafuChqVz7-YdVRkyTtDUABtvTG0',
    appId: '1:577701324258:ios:e8a3bbb009195d03fd45bb',
    messagingSenderId: '577701324258',
    projectId: 'mynotes-492a9',
    storageBucket: 'mynotes-492a9.appspot.com',
    iosBundleId: 'com.hello.mynotes.RunnerTests',
  );
}
